version: "3.7"

services: 
    flask:
        container_name: flask
        image: "flask:test"
        restart: always
        ports:
            - "5000:5000"

    nginx:
        container_name: nginx
        image: "nginx:test"
        restart: always
        ports:
            - "80:80"
