version: "3.7"

services: 
    flask:
        image: rilac1/job-crawler-module_flask
        container_name: flask
        restart: always
        environment: 
            - APP_NAME=FlaskTest
        expose:
            - 8080

    nginx:
        image: rilac1/job-crawler-module_nginx
        container_name: nginx
        restart: always
        ports:
            - "5000:5000"
            